name: Deploy backend from master branch

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'

defaults:
  run:
    working-directory: ./apps/backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest  

    steps:    
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install NPM packages
        run: |
          npm ci
      
      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "cd ./apps/backend && serverless deploy --verbose"
          entrypoint: /bin/sh
        env:
          LOG_LEVEL: debug
          DEPLOYMENT_BUCKET_NAME: ${{ vars.DEPLOYMENT_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}