name: Frontend app code checker

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

defaults:
  run:
    working-directory: ./apps/frontend

jobs:
  code-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install NPM packages
        run: |
          npm ci
          npx next telemetry disable

      - name: Run lint
        run: |
          npm run lint

      - name: Run test
        run: |
          npm run test

      - name: Run build
        run: |
          npm run build
